# Generated by Django 3.2.5 on 2022-05-12 07:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otStartTime', models.TimeField()),
                ('otEndTime', models.TimeField()),
                ('otDate', models.DateField()),
                ('otLocation', models.CharField(max_length=255)),
                ('booked', models.BooleanField(default=False)),
                ('Professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hosts', to='accounts.myuser')),
                ('booked_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='guests', to='accounts.myuser')),
            ],
        ),
    ]
