# Generated by Django 3.1.1 on 2022-04-18 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otStartTime', models.TimeField()),
                ('otEndTime', models.TimeField()),
                ('otDate', models.DateField()),
                ('otLocation', models.CharField(max_length=255)),
                ('booked', models.BooleanField(default=False)),
            ],
        ),
    ]
