# Generated by Django 3.2.5 on 2022-04-17 00:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('OfficeHour', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeslot',
            name='Professor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hosts', to='accounts.my_user'),
        ),
        migrations.AddField(
            model_name='timeslot',
            name='booked_by',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='guests', to='accounts.my_user'),
        ),
    ]
