# Generated by Django 3.2.5 on 2022-04-17 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OfficeHour', '0003_auto_20220418_0040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeslot',
            name='otDate',
            field=models.DateField(),
        ),
    ]
