# Generated by Django 3.2.5 on 2022-04-17 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_my_user_identity'),
        ('OfficeHour', '0005_alter_timeslot_booked_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeslot',
            name='booked_by',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='guests', to='accounts.my_user'),
        ),
    ]
