# Generated by Django 3.1.1 on 2022-04-18 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='forumPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=255)),
                ('Content', models.TextField()),
                ('Tag', models.CharField(max_length=255)),
                ('Poster', models.CharField(max_length=255)),
                ('Ctime', models.DateTimeField()),
                ('UpdateTime', models.DateTimeField()),
            ],
            options={
                'ordering': ['-UpdateTime'],
            },
        ),
        migrations.CreateModel(
            name='forumComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Content', models.TextField()),
                ('Ctime', models.DateTimeField()),
                ('Commenter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Commenter', to='accounts.my_user')),
                ('forumPost', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='forum.forumpost')),
            ],
            options={
                'ordering': ['Ctime'],
            },
        ),
    ]
