# Generated by Django 3.1.1 on 2022-04-18 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forumpost',
            name='Poster',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Poster', to='accounts.my_user'),
        ),
    ]
