# Generated by Django 3.2.5 on 2022-04-03 08:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='my_user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userID', models.CharField(max_length=32, unique=True)),
                ('userName', models.CharField(max_length=32, unique=True)),
                ('userEmail', models.EmailField(blank=True, max_length=254, unique=True)),
                ('identity', models.CharField(choices=[('staff', 'staff'), ('student', 'student')], default='Student', max_length=16)),
                ('has_confirmed', models.BooleanField(default=False)),
                ('c_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-c_time'],
            },
        ),
        migrations.CreateModel(
            name='ConfirmString',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=256)),
                ('c_time', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.user')),
            ],
            options={
                'verbose_name': 'Confirmation_Code',
                'verbose_name_plural': 'Confirmation_Codes',
                'ordering': ['-c_time'],
            },
        ),
    ]
