# Generated by Django 3.2.5 on 2022-04-17 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='my_user',
            name='identity',
            field=models.CharField(choices=[('faculty', 'faculty'), ('student', 'student'), ('admin', 'admin')], default='student', max_length=16),
        ),
    ]
